### ISSUE TITLE
Rename the project to "Lixo API"

### ISSUE THREAD

**Issue by Bonaro** [ThePuzzler/qlib#1]

**Comment by ThePuzzler** [comment]
ha-ha engraçado pra caralho wow muito engraçado

**Comment by evilfactory** [comment]
olha bonoro lixo api e quando usa expression 2 mas as funçoes lixos do glua realmente precisam de uma api

**Comment by Bonaro** [comment]
ainda acho que o nome seria melhor de lixo api

**Comment by evilfactory** [comment]
a api do expression 2 sim seria bom o nome lixo api

**Comment by ThePuzzler** [comment]
"LixoAPI" = PuzzleAPI -> uma lib pra EGP, já que a egplib é lixo
QLib -> uma lib pra gmod vgui, já que draw e surface são lixo
